# this file is sample format for credentials.yml.enc
# first you have to create your master.key file and then run `EDITOR=vim rails credentials:edit` and set your values.

# aws:
#   access_key_id: 123
#   secret_access_key: 345

# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: 014dde5f3416f60f0e5b6137ce896724567dc83abf906c8a171a1067488084613b6bdabe4588568bb372195923eb784684e19ce0ad7855c07be9e11be1690d5e