default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { 'postgres' } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { 'postgres' } %>
  host: <%= ENV.fetch("DATABASE_HOST") { 'localhost' } %>
  port: <%= ENV.fetch("DATABASE_PORT") { '5432' } %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME_DEVELOPMENT") { 'reactor-ant_development' } %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME_TEST") { 'reactor-ant_test' } %>

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME_PRODUCTION") { 'reactor-ant_production' } %>
